# install.packages("knitr")
# install.packages("dplyr")
# install.packages("magrittr")
# install.packages("Rtsne")
# install.packages("dendextend")
# install.packages("d3heatmap")
# install.packages("bnlearn")
# install.packages("rmarkdown")
# install.packages("ROCR")


source("https://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
biocLite("GEOquery")
biocLite("GEOquery")
biocLite("simpleaffy")
biocLite("genefilter")
biocLite("limma")
biocLite("hgu133plus2.db")
biocLite("annotate")
biocLite("preprocessCore")
